all: gauss_jordan.c gauss_seidel.c	
	gcc -o gauss_jordan gauss_jordan.c -lm
	gcc -o gauss_seidel gauss_seidel.c -lm

gauss_jordan: gauss_jordan.c
	gcc -o gauss_jordan gauss_jordan.c -lm


gauss_seidel: gauss_seidel.c
	gcc -o gauss_seidel gauss_seidel.c -lm

clean: 
	rm gauss_jordan
	rm gauss_seidel



