all:
	gcc -o bindec bindec.c -lm
	gcc -o quad quad.c -lm
	gcc -o seq seq.c 

bindec:
	gcc -o bindec bindec.c -lm

quad:
	gcc -o quad quad.c -lm

seq:
	gcc -o seq seq.c 

clean:
	rm bindec
	rm quad
	rm seq 
